sudo: false  # Container Based
language: python
python:
  - "2.7"
  - "3.4"
  - "3.5"
  - "3.6"
  - "nightly"

install:
  - pip install -r requirements.txt
  - pip install -e .

script:
  - python setup.py test
