version: 2

references:
  test_code: &test_code
    steps:
      - checkout
      - run:
          name: Check Python version
          command: |
            python -V
      - run:
          name: Prepare for running tests
          command: |
            pip install --user -r requirements.txt
            pip install --user codecov coverage
            touch README.rst
            pip install --user -e .
      - run:
          name: Run test
          command: |
            python setup.py test
            export PATH=$HOME/.local/bin:$PATH
            factordb 1
            factordb --json 16
      - run:
          name: Run coverage
          command: |
            export PATH=$HOME/.local/bin:$PATH
            coverage run setup.py test
      - run:
          name: Run codecov
          command: |
            export PATH=$HOME/.local/bin:$PATH
            codecov

jobs:
  python2:
    docker:
      - image: circleci/python:2.7
    <<: *test_code

  python34:
    docker:
      - image: circleci/python:3.4
    <<: *test_code

  python35:
    docker:
      - image: circleci/python:3.5
    <<: *test_code

  python36:
    docker:
      - image: circleci/python:3.6
    <<: *test_code

  python_latest:
    docker:
      - image: circleci/python:latest
    <<: *test_code


workflows:
  version: 2
  test_all_python_versions:
    jobs:
      - python2
      - python34
      - python35
      - python36
      - python_latest
